---
title: "Resume"
---

<hr>

## Key Skills

* Computer Programming (R, Python, SQL)
*	Microsoft Office
*	Time Management
* Data Analysis
*	Problem Solving
*	Proactive learner and worker
* Detail Oriented
*	Research skills
* Ability to effectively work remotely, over Zoom, and in person

## Education

* **Western Guilford High School** <br>
2014-2018 | High School Diploma | Microsoft Office Specialist

* **Appalachian State University Undergraduate Degree** <br>
2019-2021 | B.S. Mathematics | Statistics Concentration and Minor | Sports Analytics Certificate | 3.71 GPA

* **Appalachian State University Graduate School** <br>
2021-Present | M.A. Mathematics, College Teaching concentration | Graduate Business Analytics Certificate

## Experience

* **Appalachian State University Baseball** <br>
*Assistant Director of Data Analytics* <br>
Operate and organize data from the baseball tagging system, Trackman. The data was compiled and displayed using various graphics to present to coaches to make informed decisions about coaching strategies. Also tasked to conduct research study on pitch framing to determine the most effective catcher, providing a detailed report explaining mathematical methods and data analysis to efficiently communicate understanding to the coaching staff.

* **Teacher's Assistant** <br>
Assist a professor in grading and teaching students in a College Algebra course at Appalachian State University, as well as tutor students with any mathematical questions.

* **Boone Bigfoots Baseball** <br>
*Director of Analytics and Official Scorekeeper* <br>
Operate the scorekeeping application, GameChanger, and the baseball tagging system, Trackman. Organize and compile data from GameChanger and Trackman into a website used by our coaches to understand player performance. Website was also used to keep collegiate coaches informed on player performance. Created an umpire report to determine how accurate an umpire called balls and strikes at MLB level precision.

* **American Legion Post 53 Redwings** <br>
*Assistant coach | Director of Social Media | 2020-Present* <br>
Assist in organizing, creating, and coaching a team of 18 high school baseball players, identified as potential collegiate athletes. Communicate upcoming events and announcements via social media while maintaining proper company image.

* **Big Data Cup** <br>
Conducted two research studies in hockey data, demonstrating statistical techniques and accurate graphics to deposit the exact location and quantity of data points.

<hr>